version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password